### ISSUE TITLE
構文木の表現方法を決めたいぞ

### ISSUE THREAD

**Issue by 1995hnagamin** [kmc-jp/c89-compiler#1]
```
typedef struct {
   // everything
} Node;
```

**Comment by 1995hnagamin** [comment]
最高の資料
http://www.fos.kuis.kyoto-u.ac.jp/~umatani/le3b/siryo.pdf

**Comment by hatsusato** [comment]
C++世界にいる間は`ASTBase`を継承するなどして実装するといいと思う。
継承の階層を深くするとCに移植しづらくなるので継承は1段階の単一継承まで。
C世界に行く時には`union`を使って再現できると思う。

**Comment by 1995hnagamin** [comment]
以降 #26 で議論したほうが良さそう?
