### ISSUE TITLE
本が届かないので催促

### ISSUE THREAD

**Issue by tyage** [kmc-jp/c89-compiler#2]
http://infostore.saiglobal.com/store/Details.aspx?productID=434093

2015/09/15に注文したけどまだ届かないゾ

**Comment by primenumber** [comment]
英語苦手なのでどういう文面で送ればいいかわからないので助けてもらえませんか

**Comment by pastak** [comment]
```
Do you know "20"? Can you count up to "20"? I teach you "20" is not "30". It's very important things!
Thanks!!
```

**Comment by primenumber** [comment]
9/15にhttp://infostore.saiglobal.com/store/Details.aspx?productID=434093を頼んだけどまだ届いてない、どうなってるんだ　みたいなことを言えばいいのかな

**Comment by primenumber** [comment]
英語わからず

**Comment by t-uda** [comment]
とりあえず書いてみてここに貼り付けるんだ（見てる人誰かが添削するやろ）

**Comment by primenumber** [comment]
I ordered http://infostore.saiglobal.com/store/Details.aspx?productID=434093 on September 15.
However, it has not arrived yet.
Dounattennnen

**Comment by 1995hnagamin** [comment]
Don't you forget to send us the document?
Could you explain why you haven't fulfilled your obligation (Japanese Dounattennnen)?

**Comment by hatsusato** [comment]
Subject: Confirmation of Product Arrival Time
Contents:
Dear SAI GLOBAL,

I still haven't recieved your product http://infostore.saiglobal.com/store/Details.aspx?productID=434093 ordered on September 15.
The product page says that the delivery time to Japan is 10-20 days.
Could you tell me the time when the product is actually arrived?

Thanks,

[注文時の名義].

**Comment by sorah** [comment]
発送はもうされてるんですか?

**Comment by primenumber** [comment]
どうなんだろう、発送しました的なメールは来てないので、まだである可能性もある

**Comment by 1995hnagamin** [comment]
hatsusatoさんの良いのでは

**Comment by primenumber** [comment]
とりあえずメール出した

**Comment by 1995hnagamin** [comment]
:+1:

**Comment by nonylene** [comment]
prime++

**Comment by primenumber** [comment]
返信が来ました

> Dear Junichi 
>
>
> Thank you for your email. As the purchase was made during September/15 and delivery is up to 20 days, this order needs to be resend. 
>
> Please confirm your shipping address: 
> Mr Junichi Kanai
> 31 Daisanokadasou 108 Tanakakamiyanagicho
> Sakyo, Kyoto
> Kyoto 606-8205 Japan
> 
> Awaiting your advise. 
> Regards, Sanja

**Comment by primenumber** [comment]
住所は合っているので同じ場所にもう一度送ってくれと返信した。

**Comment by primenumber** [comment]
続報

> Thanks [name]
>
> The resend will take another 3 weeks as this is the original book sent from the ISO publisher (Europe). 
>
> I will email you tracking no. once the order is ready to ship.

**Comment by 1995hnagamin** [comment]
o

**Comment by nna774** [comment]
本が届くのを待つとか悠長なこと言ってられなさそうな雰囲気だ。

**Comment by primenumber** [comment]
たしかに。

**Comment by hatsusato** [comment]
本が届いたら急いでみんなで仕様を読み込みましょう。

**Comment by primenumber** [comment]
発送されたみたいです

> Dear [name]
> 
> ISO/IEC 9899:1990 was shipped to you via Express Courier International - tracking no. [tracking no].

**Comment by hatsusato** [comment]
無事届きました。
