### ISSUE TITLE
マージ戦略を決める

### ISSUE THREAD

**Issue by 1995hnagamin** [kmc-jp/c89-compiler#7]
マージ戦略を決めてないので僕が送った有益なPRがmasterにマージできません。なんとかしてください。
ブランチの運用方法とかマージするときのポリシーを決めましょう。

**Comment by nna774** [comment]
#6 とか(#5とか)をマージしたい！

**Comment by tyage** [comment]
そこまで気負わずに、誰かがLGTMしたら適当にマージとかでいいと思う

**Comment by nna774** [comment]
それぐらいで良さそう。

**Comment by 1995hnagamin** [comment]
じゃあそれで
