### ISSUE TITLE
テスト用コードを書く

### ISSUE THREAD

**Issue by primenumber** [kmc-jp/c89-compiler#8]
コンパイラのテストに用いるC89のソースコードがなるべくたくさん必要です。
testsディレクトリとか作ってどんどん放り込めばよい？
テストに関する知識が不足しているので、どうするのがいいか教えてください

**Comment by nna774** [comment]
とりあえず /tests とかにどんどん突っ込んでいけばいいのでは。

​適当にCI設定していけばよさそう。

**Comment by primenumber** [comment]
#9

**Comment by nna774** [comment]
とりあえず resolved by #9
