### ISSUE TITLE
Flex 2.6でビルドに失敗する

### ISSUE THREAD

**Issue by primenumber** [kmc-jp/c89-compiler#81]
Flexがversion2.6である環境でビルドすると生成されたlex.yy.c内にC++スタイルのコメントが入るので、ビルドに失敗します。
原因はsrc/skel.c:2564により、非C++向けコードが生成される場所でC++スタイルのコメントが生成されるためです。
対処:
- Flexにバグ報告をして修正を待つ
- 当面Flex2.5以下を使う

**Comment by primenumber** [comment]
(参考) 各環境でのFlexのバージョン:

- ring (Debian Wheezy): 2.5.35
- reed (Debian sid): 2.5.39
- ringo (Debian jessie): 2.5.39
- 私の手元 (Arch Linux): 2.6.0

**Comment by hatsusato** [comment]
なるほど。reedと[Travis](https://travis-ci.org/kmc-jp/c89-compiler/builds/91983619)(2.5.35)でしか開発してなかったから気づかなかった。
それは良くないバージョンですね。

**Comment by nna774** [comment]
すごい。

**Comment by primenumber** [comment]
Debian sidもFlex 2.6になっているので早めに対処する必要がある

**Comment by primenumber** [comment]
DebianのFlexでは治っているらしい

**Comment by primenumber** [comment]
2.6.0-4で修正されていました http://metadata.ftp-master.debian.org/changelogs/main/f/flex/flex_2.6.0-11_changelog

**Comment by primenumber** [comment]
Archでも2.6.0-2で修正されていそう

**Comment by primenumber** [comment]
ということで時が解決しました
